# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UmapGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

from matplotlib.backends.qt_compat import QtCore, QtWidgets, is_pyqt5
if is_pyqt5():
    from matplotlib.backends.backend_qt5agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
else:
    from matplotlib.backends.backend_qt4agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure

class Ui_Umap(object):
    def setupUi(self, Umap):
        Umap.setObjectName("Umap")
        Umap.resize(610, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Umap.sizePolicy().hasHeightForWidth())
        Umap.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Umap)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.GV = FigureCanvas(Figure(figsize=(6, 6)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.GV.sizePolicy().hasHeightForWidth())
        self.gridLayout.addWidget(self.GV, 6, 6, 3, 1)
        self.GV21 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV21.sizePolicy().hasHeightForWidth())
        self.GV21.setSizePolicy(sizePolicy)
        self.GV21.setObjectName("GV21")
        self.gridLayout.addWidget(self.GV21, 7, 1, 1, 1)
        self.GV12 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV12.sizePolicy().hasHeightForWidth())
        self.GV12.setSizePolicy(sizePolicy)
        self.GV12.setObjectName("GV12")
        self.gridLayout.addWidget(self.GV12, 6, 2, 1, 1)
        self.GV22 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV22.sizePolicy().hasHeightForWidth())
        self.GV22.setSizePolicy(sizePolicy)
        self.GV22.setObjectName("GV22")
        self.gridLayout.addWidget(self.GV22, 7, 2, 1, 1)
        self.MD2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MD2.setDecimals(2)
        self.MD2.setMaximum(1.0)
        self.MD2.setSingleStep(0.1)
        self.MD2.setProperty("value", 0.3)
        self.MD2.setObjectName("MD2")
        self.gridLayout.addWidget(self.MD2, 1, 2, 1, 1)
        self.GV33 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV33.sizePolicy().hasHeightForWidth())
        self.GV33.setSizePolicy(sizePolicy)
        self.GV33.setObjectName("GV33")
        self.gridLayout.addWidget(self.GV33, 8, 3, 1, 1)
        self.MD1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MD1.setDecimals(2)
        self.MD1.setMaximum(1.0)
        self.MD1.setSingleStep(0.1)
        self.MD1.setProperty("value", 0.1)
        self.MD1.setObjectName("MD1")
        self.gridLayout.addWidget(self.MD1, 1, 1, 1, 1)
        self.GV23 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV23.sizePolicy().hasHeightForWidth())
        self.GV23.setSizePolicy(sizePolicy)
        self.GV23.setObjectName("GV23")
        self.gridLayout.addWidget(self.GV23, 7, 3, 1, 1)
        self.MD3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MD3.setDecimals(2)
        self.MD3.setMaximum(1.0)
        self.MD3.setSingleStep(0.1)
        self.MD3.setProperty("value", 0.8)
        self.MD3.setObjectName("MD3")
        self.gridLayout.addWidget(self.MD3, 1, 3, 1, 1)
        self.GV13 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV13.sizePolicy().hasHeightForWidth())
        self.GV13.setSizePolicy(sizePolicy)
        self.GV13.setObjectName("GV13")
        self.gridLayout.addWidget(self.GV13, 6, 3, 1, 1)
        self.GV11 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV11.sizePolicy().hasHeightForWidth())
        self.GV11.setSizePolicy(sizePolicy)
        self.GV11.setObjectName("GV11")
        self.gridLayout.addWidget(self.GV11, 6, 1, 1, 1)
        self.GV31 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV31.sizePolicy().hasHeightForWidth())
        self.GV31.setSizePolicy(sizePolicy)
        self.GV31.setObjectName("GV31")
        self.gridLayout.addWidget(self.GV31, 8, 1, 1, 1)
        self.NN3 = QtWidgets.QSpinBox(self.centralwidget)
        self.NN3.setMaximum(1000)
        self.NN3.setSingleStep(5)
        self.NN3.setProperty("value", 100)
        self.NN3.setObjectName("NN3")
        self.gridLayout.addWidget(self.NN3, 8, 0, 1, 1)
        self.NN2 = QtWidgets.QSpinBox(self.centralwidget)
        self.NN2.setMaximum(1000)
        self.NN2.setSingleStep(5)
        self.NN2.setProperty("value", 20)
        self.NN2.setObjectName("NN2")
        self.gridLayout.addWidget(self.NN2, 7, 0, 1, 1)
        self.Detail = QtWidgets.QPushButton(self.centralwidget)
        self.Detail.setObjectName("Detail")
        self.gridLayout.addWidget(self.Detail, 1, 6, 1, 1)
        self.NN1 = QtWidgets.QSpinBox(self.centralwidget)
        self.NN1.setMaximum(1000)
        self.NN1.setSingleStep(5)
        self.NN1.setProperty("value", 5)
        self.NN1.setObjectName("NN1")
        self.gridLayout.addWidget(self.NN1, 6, 0, 1, 1)
        self.GV32 = FigureCanvas(Figure(figsize=(1, 1)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GV32.sizePolicy().hasHeightForWidth())
        self.GV32.setSizePolicy(sizePolicy)
        self.GV32.setObjectName("GV32")
        self.gridLayout.addWidget(self.GV32, 8, 2, 1, 1)
        self.OP = QtWidgets.QComboBox(self.centralwidget)
        self.OP.setObjectName("OP")
        self.OP.addItem("")
        self.OP.addItem("")
        self.OP.addItem("")
        self.OP.addItem("")
        self.gridLayout.addWidget(self.OP, 1, 0, 1, 1)
        Umap.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Umap)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 22))
        self.menubar.setObjectName("menubar")
        self.menuUmap = QtWidgets.QMenu(self.menubar)
        self.menuUmap.setObjectName("menuUmap")
        Umap.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Umap)
        self.statusbar.setObjectName("statusbar")
        Umap.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuUmap.menuAction())

        self.retranslateUi(Umap)
        QtCore.QMetaObject.connectSlotsByName(Umap)

    def retranslateUi(self, Umap):
        _translate = QtCore.QCoreApplication.translate
        Umap.setWindowTitle(_translate("Umap", "UmapDimensioReduction"))
        self.Detail.setText(_translate("Umap", "Processing"))
        self.OP.setItemText(0, _translate("Umap", "Iris"))
        self.OP.setItemText(1, _translate("Umap", "MINIST"))
        self.OP.setItemText(2, _translate("Umap", "F MINIST"))
        self.OP.setItemText(3, _translate("Umap", "Swiss Roll"))
        self.menuUmap.setTitle(_translate("Umap", "Umap"))
