# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mini_frame1 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame1.setObjectName("mini_frame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mini_frame1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_1 = QtWidgets.QLabel(self.mini_frame1)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_3.addWidget(self.label_1, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame1, 0, 0, 1, 1)
        self.mini_frame2 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame2.setObjectName("mini_frame2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mini_frame2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.mini_frame2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame2, 0, 1, 1, 1)
        self.mini_frame3 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame3.setObjectName("mini_frame3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.mini_frame3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.mini_frame3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame3, 0, 2, 1, 1)
        self.mini_frame4 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame4.setObjectName("mini_frame4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.mini_frame4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.mini_frame4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame4, 1, 0, 1, 1)
        self.mini_frame5 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame5.setObjectName("mini_frame5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mini_frame5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.mini_frame5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame5, 1, 1, 1, 1)
        self.mini_frame6 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame6.setObjectName("mini_frame6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.mini_frame6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_6 = QtWidgets.QLabel(self.mini_frame6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame6, 1, 2, 1, 1)
        self.mini_frame7 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame7.setObjectName("mini_frame7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.mini_frame7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_7 = QtWidgets.QLabel(self.mini_frame7)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame7, 2, 0, 1, 1)
        self.mini_frame8 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame8.setObjectName("mini_frame8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.mini_frame8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_8 = QtWidgets.QLabel(self.mini_frame8)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame8, 2, 1, 1, 1)
        self.mini_frame9 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame9.setObjectName("mini_frame9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.mini_frame9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_9 = QtWidgets.QLabel(self.mini_frame9)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame9, 2, 2, 1, 1)
        self.mini_frame10 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame10.setObjectName("mini_frame10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.mini_frame10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_10 = QtWidgets.QLabel(self.mini_frame10)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame10, 3, 0, 1, 1)
        self.mini_frame11 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame11.setObjectName("mini_frame11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.mini_frame11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_11 = QtWidgets.QLabel(self.mini_frame11)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame11, 3, 1, 1, 1)
        self.mini_frame12 = QtWidgets.QFrame(self.centralwidget)
        self.mini_frame12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_frame12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_frame12.setObjectName("mini_frame12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.mini_frame12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_12 = QtWidgets.QLabel(self.mini_frame12)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_frame12, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.frame_big = QtWidgets.QFrame(self.centralwidget)
        self.frame_big.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_big.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_big.setObjectName("frame_big")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_big)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_figure = QtWidgets.QFrame(self.frame_big)
        self.frame_figure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_figure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_figure.setObjectName("frame_figure")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_figure)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_big = QtWidgets.QLabel(self.frame_figure)
        self.label_big.setAlignment(QtCore.Qt.AlignCenter)
        self.label_big.setObjectName("label_big")
        self.gridLayout_15.addWidget(self.label_big, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_figure)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_detail = QtWidgets.QPushButton(self.frame_big)
        self.btn_detail.setObjectName("btn_detail")
        self.horizontalLayout_2.addWidget(self.btn_detail)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.gridLayout_16.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_big)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 816, 32))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "placeholder"))
        self.label_2.setText(_translate("MainWindow", "placeholder"))
        self.label_3.setText(_translate("MainWindow", "placeholder"))
        self.label_4.setText(_translate("MainWindow", "placeholder"))
        self.label_5.setText(_translate("MainWindow", "placeholder"))
        self.label_6.setText(_translate("MainWindow", "placeholder"))
        self.label_7.setText(_translate("MainWindow", "placeholder"))
        self.label_8.setText(_translate("MainWindow", "placeholder"))
        self.label_9.setText(_translate("MainWindow", "placeholder"))
        self.label_10.setText(_translate("MainWindow", "placeholder"))
        self.label_11.setText(_translate("MainWindow", "placeholder"))
        self.label_12.setText(_translate("MainWindow", "placeholder"))
        self.label_big.setText(_translate("MainWindow", "placeholder"))
        self.btn_detail.setText(_translate("MainWindow", "Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

